// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKOji7_ujqiOUN5s-60JAg3bM_A9QQhEs',
    appId: '1:713501543104:web:8afdfa09914d92f6503b25',
    messagingSenderId: '713501543104',
    projectId: 'freshtally8',
    authDomain: 'freshtally8.firebaseapp.com',
    storageBucket: 'freshtally8.firebasestorage.app',
    measurementId: 'G-01EMQD05VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbV5w8hrvddt0IEcswX9AUGMnfczUJU_M',
    appId: '1:713501543104:android:93fa2bc798429967503b25',
    messagingSenderId: '713501543104',
    projectId: 'freshtally8',
    storageBucket: 'freshtally8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKXMaiyq-XoNuW5iZ2PAWENNhJl_I4kSs',
    appId: '1:713501543104:ios:bd002b2db42f9b5a503b25',
    messagingSenderId: '713501543104',
    projectId: 'freshtally8',
    storageBucket: 'freshtally8.firebasestorage.app',
    iosBundleId: 'com.example.freshtally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKXMaiyq-XoNuW5iZ2PAWENNhJl_I4kSs',
    appId: '1:713501543104:ios:bd002b2db42f9b5a503b25',
    messagingSenderId: '713501543104',
    projectId: 'freshtally8',
    storageBucket: 'freshtally8.firebasestorage.app',
    iosBundleId: 'com.example.freshtally',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKOji7_ujqiOUN5s-60JAg3bM_A9QQhEs',
    appId: '1:713501543104:web:050269a0e65de8b7503b25',
    messagingSenderId: '713501543104',
    projectId: 'freshtally8',
    authDomain: 'freshtally8.firebaseapp.com',
    storageBucket: 'freshtally8.firebasestorage.app',
    measurementId: 'G-MR3EYWZTNX',
  );
}
